### ISSUE TITLE
[Critical] getJoinedTermsByState does not return the correct values

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#103]
See Image below to compare what `getAllJoinedTerms `and `getJoinedTermsByState `returns. 

Line70 assigns index. Should be ` userTermsByState[termscounter] = joinedTerms[i]`
In addition, rather than deciding userTermsByState length, just push the values. Otherwise, you will return an array filled with 0's which will cause bugs on the fronend. 

![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/130288542/fe0dd21e-a163-4506-bcef-5fcd20582a37)

https://github.com/TakafulDAO/takaturn-phase-2/blob/fbd6aca3ad7953891939acca04db0d075bf31ab6/contracts/facets/GettersFacet.sol#L60-L80

**Comment by elallamTaka** [comment]
@maikelordaz Please write unit tests for this. You can use this wallet if you want since it has joined 5 terms: 0xca01ec47798B8Dd0708BBe0855DdB35bC66D959F

**Comment by maikelordaz** [comment]
The problem is that in solidity memorys arrays does not have either push or pop properties, those are reserved to storage arrays. It is fixed on commit 0a45afd. The outputs are like this now, only the length corresponding to valid values
![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/8f9658ba-60e6-4263-bf2b-e742604305a8)
