### ISSUE TITLE
User should be able to withdraw collateral if expelled

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#106]
https://github.com/TakafulDAO/takaturn-phase-2/blob/f360512368ebb81c222b8e97f2d10f6bbcea9862/contracts/facets/CollateralFacet.sol#L164

This is an edge case for when someone get expelled but keeps some collateral (when expelled before being beneficiary). This person should still be able to withdraw collateral

**Comment by MohammedTaka** [comment]
cc @elallamTaka is this edge case also tackled on the front end?

**Comment by MohammedTaka** [comment]
This must also be done with

https://github.com/TakafulDAO/takaturn-phase-2/blob/f360512368ebb81c222b8e97f2d10f6bbcea9862/contracts/facets/GettersFacet.sol#L225

**Comment by elallamTaka** [comment]
> This must also be done with

Didnt have a use case where someone got expelled on the front end yet. But this is a valid issue. 
So the condition is (isExpelled is true && wasBeneficiary is false) ?

**Comment by MohammedTaka** [comment]
> > This must also be done with
> 
> Didnt have a use case where someone got expelled on the front end yet. But this is a valid issue. So the condition is (isExpelled is true && wasBeneficiary is false) ?

Yes this is the right condition

**Comment by elallamTaka** [comment]
My proposed fix for this issue is as follows: 
1) `getWithdrawableUserBalance `should return 2 values: `unlockedCollateral`, `unlockedYield`. 
2) `getWithdrawableUserBalance `should make the check to see if an expelled member has balance to withdraw. 
3) `withdrawCollateral `should call `getWithdrawableUserBalance`, they share duplicate logic.

These fixes must not be deployed to testnet yet.

**Comment by elallamTaka** [comment]
To fix, add condition isExpelled: 
`        if (collateral.state == LibCollateralStorage.CollateralStates.ReleasingCollateral) `

**Comment by maikelordaz** [comment]
Merged
