### ISSUE TITLE
Arithmetic bug on _withdrawYG

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#141]
Testing the return values from zayn vault I got this any time somebody was withdrawing collateral or anybody defaults. 
<img width="691" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/f23361ae-eb89-40fe-aed3-c41f23991868">
I was pretty sure it was this line 
https://github.com/TakafulDAO/takaturn-phase-2/blob/e586bbdab006dc4b92fd697f23dad9b7aa56488c/contracts/libraries/LibYieldGeneration.sol#L58
And got confirmation simulating on tenderly (as our contract is also forked on the tests I can not log any values on terminal when running the tests
![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/02305f75-629b-49e8-aa57-12ee4fc5c3db)
@MohammedTaka I'll set it as 
```solidity
uint withdrawnYield += withdrawnAmount;
```

**Comment by maikelordaz** [comment]
Just for context. 

<h2>Simulation params:</h2>
- registrationPeriod = 604800</br>
- totalParticipants = 4</br>
- cycleTime = 2592002</br>
- contributionAmount = 250</br>
- contributionPeriod = 43200</br>

<h2>Collateral Deposited: (the minimum for each)</h2>
- Participant 1 = 962155227710070558 wei</br>
- Participant 2 = 721616420782552918 wei</br>
- Participant 3 = 481077613855035279 wei</br>
- Participant 4 = 240538806927517639 wei</br>
- Deposited on yield = 2405388069275176394 wei</br>

<h2>Everyone defaults the first cycle</h2>
- Collateral liquidated for participant 2 = 160359204618345093 wei (contribution amount in wei)</br>
- This is the amount used to call _withdrawFromYield and _withdrawYG</br>

<h2>_ethToShares:</h2>
- collateralAmount = collateral liquidated</br>
- totalShares = 2400801799401252873 LP tokens</br>
- totalDeposit = 2405388069275176394 wei</br>
- Return value = 160053453293416858 LP tokens (used to call zapOut)</br>

<h2>zapOut:</h2>
- Return value = 160207135011630536</br>

<h2>Underflow:</h2>
- zapOut = 160207135011630536 wei</br>
- Collateral Liquidated = 160359204618345093 wei</br>
- Result = -152069606714976 wei</br>

**Comment by maikelordaz** [comment]
@MohammedTaka after several simulations and checking the values, think the problem is in `_ethToShares` maybe `balanceOf` does not return what we think?

**Comment by MohammedTaka** [comment]
The bug is in _depositYG

the shares is not calculated correctly. We are getting the shares (balanceOf) AFTER zapIn. We must call balanceOf before AND after zapIn. And calculate the difference (balanceOf after should be higher)

https://github.com/TakafulDAO/takaturn-phase-2/blob/e586bbdab006dc4b92fd697f23dad9b7aa56488c/contracts/libraries/LibYieldGeneration.sol#L28

so:
`uint sharesBefore = balanceOf();
zapIn()
uint sharesAfter = balanceOf
yield.totalShares = sharesAfter - sharesBefore;`

@maikelordaz 

cc @elallamTaka

**Comment by maikelordaz** [comment]
The balanceOf before is zero. As there is nothing deposited

**Comment by maikelordaz** [comment]
<img width="332" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/12d15086-f984-4a36-aefd-46fe3a6874fe">

![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/5d7f2e40-de3d-4044-a009-e42cf7538929)

Taken from the deployed zayn vault contract

**Comment by maikelordaz** [comment]
Just for context and find it easier
<img width="469" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/0aed755d-bae4-4cf5-a1d1-84460d22e971">

**Comment by MohammedTaka** [comment]
Alright the issue comes from the fact that there are some fees involved due to swapping WETH to and from FRXETH.

To mitigate this, for now we will only deposit 90% of the collateral and use the remaining 10% to cover for fees. The logic will remain mostly the same.

Its 2 changes:
1. Lower the total deposit amount by 90% of the original deposit amount
2. When withdrawing, we are calculating yield by "withdrawnYield = withdrawnAmount - _collateralAmount; ". We wrap this bit and what is after it by an if statement. If withdrawn amount is lesser than, there is no yield added and the function returns with 0 as return value.

The end goal is that the beneficiary must always get what he is entitled to.

**Comment by MohammedTaka** [comment]
A fix has been deployed for now. But we need to take a look at the withdrawals and apply another hotfix if need be. Some logic might break because not all c9llateral is deposited.

**Comment by maikelordaz** [comment]
Fixed and merged
