### ISSUE TITLE
Wrong condition for expelledBeforeBeneficiary 

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#160]
The expelledBeforeBeneficiary condition returns true due to `wasExpelled(termId, msg.sender)`. This makes the withdrawable user balance greater than 0 in other collater states such as AcceptingCollateral.

Fix: 
`wasExpelled(termId, user).`

https://github.com/TakafulDAO/takaturn-phase-2/blob/54db23797d55b69e31c5eb40a7426a1e2aed4977/contracts/facets/GettersFacet.sol#L303-L304

The commit must also include the following unit tests, and any you can also include:

- [x] getWitdrawableBalance must be 0 in Collateral state AcceptingCollateral
- [x] getWithdrawableBalance must be > 0 for expelled user before their beneficiary turn.
- [x] getWithdrawableBalance == total locked balance for a user when Releasing Collateral
- [x] getWithdrawableBalance == total locked balance for a user expelled before being beneficiary

**Comment by maikelordaz** [comment]
- Fixed the error with the call on wasExpelled, I mistaken and wrote msg.sender instead of user, this on commit 1cf58ed
- Also fixed another expelled edge case, we were setting up the isBeneficiary mapping for the expelled participants to true so we losed track of who was expelled before being beneficiary. This on commit 444a226
