### ISSUE TITLE
Move defaulters logic to a new defaulters facet

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#35]
Selecting defaulters and the different scenarios have become very complex. Having ut all jn the collateral used to make sense because previously we only did something with the collateral and didn't touch the money pot. But now that there is a possibility to touch the money pot, it doesn’t make sense to keep thos in the collateral facet.

**Comment by elallamTaka** [comment]
I think for phase 3 a lot can change to make the code more readable and shorter. When we did the initial migration to diamond the requirement where money pot can be liquidated didn't exist. So it will make sense to revise our facets and logic. 
One big note though, if we decide to do this we need to provide a detailed document with the changes the frontend/ backend are required to change before upgrading the contract. 

We also have to pay more attention to interfacing because we dont want to make FE and BE changes each time we restructure.

**Comment by maikelordaz** [comment]
I would say more that to a new facet I would say to a library. That way we can make it internal and solve the problems with access control.

**Comment by MohammedTaka** [comment]
> I would say more that to a new facet I would say to a library. That way we can make it internal and solve the problems with access control.

Also a good option

**Comment by maikelordaz** [comment]
Moved to jira
