### ISSUE TITLE
Bug: Cannot enable autopay before the 1st cycle starts

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#61]
The user should be able to enable autopay after paying the security deposit. But it kept failing from the UXUI while testing with Khalid. 
It says needs to be a participant. 
Use Collateral storage to make the check, fund.isParticipant returns false due to not being initialized yet. 

https://github.com/TakafulDAO/takaturn-phase-2/blob/6410733eb3a1c8a4af68cab43cbf84e291188e6a/contracts/facets/FundFacet.sol#L197-L199

**Comment by maikelordaz** [comment]
All the fund variables are initialized when startTerm is called. I can move some initializations to _joinTerm so it could work. Or to change less lines, on autoPay instead of checking the isParticipant array check the isCollateralMember one. This last one is set as true as soon as the participant pays the security.

**Comment by maikelordaz** [comment]
Commit 322c735
